### ISSUE TITLE
Support for existing VNET outside of the WEKA resource group

### ISSUE THREAD

**Issue by alexpersin** [weka/terraform-azure-weka#100]
Azure best practice is to group resources for an application or solution into a resource group, in this case the WEKA deployment. When adding the deployment to an existing VNET it is possible (or likely) that the VNET is in a different resource group, and so support for deploying to an existing VNET in a different resource group is desirable.

**Comment by assafgi** [comment]
Hi,
Supporting vnet from another resource group is simple, but then it raises a question,
We have the `create_networks` module which creates network related resources like routing tables, security groups, dns zone etc. 
Is it OK from your side to create all these resources in the vnet resource group ?

**Comment by assafgi** [comment]
Fixed
