### ISSUE TITLE
Variable `function_app_dist` should default to 'release'

### ISSUE THREAD

**Issue by alexpersin** [weka/terraform-azure-weka#103]
The variable 'function_app_dist' defaults to 'dev', and is not overridden in the example deployments.  I found that this endpoint was unavailable for a period of time resulting in the deployed function app runtime not being available. Should to variable default to 'release'?

**Comment by assafgi** [comment]
Hi, this is intended, we don't want a constant distribution on all regions for a work in progress code. 
You should use only public releases, for example now it is [v2.0.0](https://github.com/weka/terraform-azure-weka/releases/tag/v2.0.0) .
